dist: trusty
build_docker_image:
  name: Test and Build docker image
  script:
  - docker build -t secret_szanta .

push_to_production:
  on:
    branch: master
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_LOGIN" --password-stdin
    - docker tag secret_szanta $DOCKER_LOGIN/secret_szanta
    - docker push $DOCKER_LOGIN/secret_szanta

env:
  matrix:
  - secure: soqsQPUNG+TPcO5Ev9N7VaZduxKKuNWCf5Jdvbx3zR4mNXE6c3nIlr9QwodBGk9c/+lzHGeoxWsIEVGb1mQtJH3symRSzTN7gQ00r0wZF94AYclJMU9k75QbpZ2/4BTbTfnG8/s9mGN9h0beDnf7SK8fYj/MQHpxkreJOlkqR2XSKoyHdLYyASZt93Xu7XjQkqUnshaHQ4dTs8Ukon29mkHHFz//MtXRdS0uVo+pNZpDSDyCJHdPvNopmi02aXahiQHhtPqk3T8ED1jmudTv7Fus3ALnqpxjnaS054j12vSRReRH67xLnhfwtBeKjxBSaLtGA0/04xLPSc2mqVitjQevk90YbOKSNIykhcwOyGApGfeYp/o3qKFsEqjjxlH2n/D9vkxIzZXDYuMcn0T2jIjFtY9Lz58YSf5WNdR+gzwWG9v9AnOBrtCGyUlD+nPYgnMiuPjPmX4H/9a3N2n2FITJFbvylE+VL0uQ77OXUbFDNE2p0cu1G6390o7uKVQPgt7sajeSFw5eLDE/tBjjqSKcgwPxFsKEgQrTkFZmDJJXTHPrX1oRUFXbadNXDpyc3A+LJlCMmusPN4hKbEOhqp2scL4HmUzHS/HZ/kuYtiDxbMoRBv7VO5JtJ77ZjhDihntVCjp0vjX08407mZU7AWIRcJgC2Fwv+zWuvluGZhM=
  - secure: KybDy/Q2t3XkT7fPNDUbIXjf9P7ZTVxDL0sWL7hpibpKMyF+gYhhLIl2lDTF1BT++5J2HHXjnCn8vnxlDls3du0GJz4/fXBpBWHSsolQsGQT3VS0BxY/0DR1N7Dd/PVddGkhxGeOndSUvNHH8bIgOgx1lZFRx0x9anO85+MukS6l089WbdoplBVXHFebYwQda9G0LFHYsCRQjJC0WRJFkice5gCgMXCUWONUIzeC58LFmiIxeyFrI4IWH0Itnr2HawQESXys1485NVsoAQxAA+be50OKNUKvYY4MUtqYZK04PpVYGdguVbV4aJMB68UMidfOBxkrRjVjGv3U8is7vtdOzZ8pROxbyJ3086MzYuWOLIPkUYs2Zbi2YME8+h/h19gY5G4kFsvBRnsAoYXxRucrbouRbedsALjNEgW+rQF+RBccqAdSzVapSA0XyLuiGF/R1Mn7Vohw/4y5yR8xQhcTwK/jxBV4fkdofYZzPprMryzTG6SWigpIoAFYyWOW3QHPIYEQtl5kW8XfYn9TWOCpAx4VbxfdlWjdFa72Xs7u5PurRlPXenaooAwwqmHYZhT55Cn4KHn4O3dNr5cEqZuPKpQUj+WSMoucPmajNKufSYU1cdmJBSTwCF4FII6HSzLgeNxYBITmDcKvV5r8bAZPOtaT5dUoE1qXjENKa5c=
