
export const PlayerDirection = {
    PLAYER_DIRECTION_LEFT: 'PLAYER_DIRECTION_LEFT',
    PLAYER_DIRECTION_UP: 'PLAYER_DIRECTION_UP',
    PLAYER_DIRECTION_RIGHT: 'PLAYER_DIRECTION_RIGHT'
}

export const PlayerRole = {
    ROLE_CHANCELLOR: 'ROLE_CHANCELLOR',
    ROLE_PRESIDENT: 'ROLE_PRESIDENT',
    ROLE_PREVIOUS_CHANCELLOR: 'ROLE_PREVIOUS_CHANCELLOR',
    ROLE_PREVIOUS_PRESIDENT: 'ROLE_PREVIOUS_PRESIDENT'
}
