export const CLIENT_SEND_MESSAGE = 'CLIENT_SEND_MESSAGE'
export const CLIENT_JOIN_ROOM = 'CLIENT_JOIN_ROOM'
export const CLIENT_LEAVE_ROOM = 'CLIENT_LEAVE_ROOM'
export const CLIENT_GET_ROOM_DATA = 'CLIENT_GET_ROOM_DATA'